name: "Github mention to Chatwork"
description: "Convert Github mention to Chatwork mention"
inputs:
  configuration-path:
    description: "Path to config-yaml-file to convert Github username to Chatwork member ID."
    required: true
    default: ".github/mention-to-chatwork.yml"
  api-token:
    description: "chatwork access token."
    required: true
  repo-token:
    description: "Github access token to fetch .github/mention-to-chatwork.yml file."
    required: true
  run-id:
    description: "Used for the link in the error message when an error occurs."
    required: false
  review-request:
    description: "need Review request "
    required: true
    default: "true"
  action:
    description: "Action name."
    deprecationMessage: "not use."
    required: false
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "message-square"
  color: "red"
